### ISSUE TITLE
Functions do not work with particular distribution families

### ISSUE THREAD

**Issue by ManfredKloebl** [CoryMcCartan/adjustr#4]
Hi,

I'm currently facing the same problem as was previously discussed here, so it seems that no solution had been found yet: https://discourse.mc-stan.org/t/new-package-for-sensitivity-analysis-using-importance-sampling/17930/6. It seems to me that only particular distribution families are affected (e.g., the zero-one-inflated beta but not the pure beta distribution). Maybe this is a starting point for analyzing the problem. Here is a toy example, which also demonstrates this:

```
library("brms")
library("adjustr")

y <- runif(100)
x <- rnorm(100)

df <- tibble(y, x)

model1 <- brm(y ~ x, data = df, family = brmsfamily("beta"), init = "0")
model2 <- brm(y ~ x, data = df, family = brmsfamily("zero_one_inflated_beta"), init = "0")

extract_samp_stmts(model1)
extract_samp_stmts(model2)
```

Many thanks for your support!

**Comment by CoryMcCartan** [comment]
Are you using the most recent development version? 

I thought we fixed this here https://github.com/CoryMcCartan/adjustr/issues/1 but perhaps not

**Comment by ManfredKloebl** [comment]
Yes, I downloaded the latest version just today and downloaded it again now to be sure. I still get this error message for the second of the above models:
```
Error in str2lang(x) : <text>:1:28: unexpected '['
1: Y ~ zero_one_inflated_beta([
                               ^
```

**Comment by CoryMcCartan** [comment]
OK, thanks, I'll take a look

**Comment by CoryMcCartan** [comment]
This should be fixed in v0.2.0, which replaces the regex-based Stan parser with a token-based parser that properly handles brace nesting and is updated to reflect changes to Stan's syntax & distributions.
